---
name: rl-olfaction
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - ipykernel
  - pip
  - matplotlib
  - jupyterlab
  - jupytext
  - ipympl
  - jupyterlab-git
  - ipdb
  - black[jupyter]
  - ruff
  - ipywidgets
  - seaborn
  - nb_black
  - pre-commit
  - tqdm
  - pandas
  - scikit-learn
  - pytorch
  - cpuonly
  # - pytorch-cuda
  # - spyder
  # - spyder-notebook
  # - torchinfo
  - pytest
  - tensordict
  - click
  - pip:
      - imojify
      - -e .
