name: CI

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: rl-olfaction
          environment-file: environment.yml
      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - shell: bash -el {0}
        run: pytest -v .
